benchmarks:
- api_misuse_jsoncpp
concurrent_builds: 30
custom_seed_corpus_dir: null
description: null
docker_registry: gcr.io/fuzzbench
experiment: d09-05-2024t10-00-57
experiment_filestore: /tmp/experiment-data
fuzzers:
- afl
- libfuzzer
- honggfuzz
- aflplusplus
- aflsmart
- aflfast
- fairfuzz
- mopt
- eclipser
git_hash: b6d7a9c8ffd4106f8929ec527f369228b835fe91
local_experiment: true
max_total_time: 120
measurers_cpus: null
micro_experiment: false
no_dictionaries: false
no_seeds: false
oss_fuzz_corpus: false
private: false
region_coverage: false
report_filestore: /tmp/report-data
runner_machine_type: n1-standard-1
runner_memory: 12GB
runner_num_cpu_cores: 1
runners_cpus: null
snapshot_period: 900
trials: 1
worker_pool_name: ''
